// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: hashmachine.proto

package hashmachine

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Hash int32

const (
	Hash_HASH_UNKNOWN Hash = 0
	Hash_HASH_SHA256  Hash = 1
)

// Enum value maps for Hash.
var (
	Hash_name = map[int32]string{
		0: "HASH_UNKNOWN",
		1: "HASH_SHA256",
	}
	Hash_value = map[string]int32{
		"HASH_UNKNOWN": 0,
		"HASH_SHA256":  1,
	}
)

func (x Hash) Enum() *Hash {
	p := new(Hash)
	*p = x
	return p
}

func (x Hash) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Hash) Descriptor() protoreflect.EnumDescriptor {
	return file_hashmachine_proto_enumTypes[0].Descriptor()
}

func (Hash) Type() protoreflect.EnumType {
	return &file_hashmachine_proto_enumTypes[0]
}

func (x Hash) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Hash.Descriptor instead.
func (Hash) EnumDescriptor() ([]byte, []int) {
	return file_hashmachine_proto_rawDescGZIP(), []int{0}
}

type OpCode int32

const (
	OpCode_OPCODE_UNKNOWN                    OpCode = 0
	OpCode_OPCODE_PUSH_INPUT                 OpCode = 1 // push input value at 'index' onto stack
	OpCode_OPCODE_PUSH_BYTES                 OpCode = 2 // push 'payload' onto the stack
	OpCode_OPCODE_POP_CHILDREN_HASH_AND_PUSH OpCode = 3 // pop metadata.branching_factor values from
	// stack, hashing each in pop order, get
	// hash sum and push onto stack
	OpCode_OPCODE_POP_N_HASH_AND_PUSH OpCode = 4 // pop 'index' values from stack, hashing
)

// Enum value maps for OpCode.
var (
	OpCode_name = map[int32]string{
		0: "OPCODE_UNKNOWN",
		1: "OPCODE_PUSH_INPUT",
		2: "OPCODE_PUSH_BYTES",
		3: "OPCODE_POP_CHILDREN_HASH_AND_PUSH",
		4: "OPCODE_POP_N_HASH_AND_PUSH",
	}
	OpCode_value = map[string]int32{
		"OPCODE_UNKNOWN":                    0,
		"OPCODE_PUSH_INPUT":                 1,
		"OPCODE_PUSH_BYTES":                 2,
		"OPCODE_POP_CHILDREN_HASH_AND_PUSH": 3,
		"OPCODE_POP_N_HASH_AND_PUSH":        4,
	}
)

func (x OpCode) Enum() *OpCode {
	p := new(OpCode)
	*p = x
	return p
}

func (x OpCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpCode) Descriptor() protoreflect.EnumDescriptor {
	return file_hashmachine_proto_enumTypes[1].Descriptor()
}

func (OpCode) Type() protoreflect.EnumType {
	return &file_hashmachine_proto_enumTypes[1]
}

func (x OpCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpCode.Descriptor instead.
func (OpCode) EnumDescriptor() ([]byte, []int) {
	return file_hashmachine_proto_rawDescGZIP(), []int{1}
}

type ProgramMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash                  Hash   `protobuf:"varint,1,opt,name=hash,proto3,enum=Hash" json:"hash,omitempty"`
	ExpectedInputCount    uint32 `protobuf:"varint,2,opt,name=expected_input_count,json=expectedInputCount,proto3" json:"expected_input_count,omitempty"`
	BranchingFactor       uint32 `protobuf:"varint,3,opt,name=branching_factor,json=branchingFactor,proto3" json:"branching_factor,omitempty"`
	HashOutputLengthBytes uint32 `protobuf:"varint,4,opt,name=hash_output_length_bytes,json=hashOutputLengthBytes,proto3" json:"hash_output_length_bytes,omitempty"`
}

func (x *ProgramMetadata) Reset() {
	*x = ProgramMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashmachine_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProgramMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramMetadata) ProtoMessage() {}

func (x *ProgramMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_hashmachine_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramMetadata.ProtoReflect.Descriptor instead.
func (*ProgramMetadata) Descriptor() ([]byte, []int) {
	return file_hashmachine_proto_rawDescGZIP(), []int{0}
}

func (x *ProgramMetadata) GetHash() Hash {
	if x != nil {
		return x.Hash
	}
	return Hash_HASH_UNKNOWN
}

func (x *ProgramMetadata) GetExpectedInputCount() uint32 {
	if x != nil {
		return x.ExpectedInputCount
	}
	return 0
}

func (x *ProgramMetadata) GetBranchingFactor() uint32 {
	if x != nil {
		return x.BranchingFactor
	}
	return 0
}

func (x *ProgramMetadata) GetHashOutputLengthBytes() uint32 {
	if x != nil {
		return x.HashOutputLengthBytes
	}
	return 0
}

type Op struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Opcode  OpCode `protobuf:"varint,1,opt,name=opcode,proto3,enum=OpCode" json:"opcode,omitempty"`
	Index   uint64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Op) Reset() {
	*x = Op{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashmachine_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Op) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Op) ProtoMessage() {}

func (x *Op) ProtoReflect() protoreflect.Message {
	mi := &file_hashmachine_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Op.ProtoReflect.Descriptor instead.
func (*Op) Descriptor() ([]byte, []int) {
	return file_hashmachine_proto_rawDescGZIP(), []int{1}
}

func (x *Op) GetOpcode() OpCode {
	if x != nil {
		return x.Opcode
	}
	return OpCode_OPCODE_UNKNOWN
}

func (x *Op) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Op) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Program struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata *ProgramMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Ops      []*Op            `protobuf:"bytes,2,rep,name=Ops,proto3" json:"Ops,omitempty"`
}

func (x *Program) Reset() {
	*x = Program{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashmachine_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Program) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Program) ProtoMessage() {}

func (x *Program) ProtoReflect() protoreflect.Message {
	mi := &file_hashmachine_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Program.ProtoReflect.Descriptor instead.
func (*Program) Descriptor() ([]byte, []int) {
	return file_hashmachine_proto_rawDescGZIP(), []int{2}
}

func (x *Program) GetMetadata() *ProgramMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Program) GetOps() []*Op {
	if x != nil {
		return x.Ops
	}
	return nil
}

var File_hashmachine_proto protoreflect.FileDescriptor

var file_hashmachine_proto_rawDesc = []byte{
	0x0a, 0x11, 0x68, 0x61, 0x73, 0x68, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xc2, 0x01, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x05, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x52, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x12, 0x30, 0x0a, 0x14, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x12, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x69, 0x6e,
	0x67, 0x5f, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f,
	0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x12,
	0x37, 0x0a, 0x18, 0x68, 0x61, 0x73, 0x68, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x6c,
	0x65, 0x6e, 0x67, 0x74, 0x68, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x15, 0x68, 0x61, 0x73, 0x68, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x4c, 0x65, 0x6e,
	0x67, 0x74, 0x68, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x55, 0x0a, 0x02, 0x4f, 0x70, 0x12, 0x1f,
	0x0a, 0x06, 0x6f, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07,
	0x2e, 0x4f, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x06, 0x6f, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22,
	0x4e, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x2c, 0x0a, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x50,
	0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x15, 0x0a, 0x03, 0x4f, 0x70, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x03, 0x2e, 0x4f, 0x70, 0x52, 0x03, 0x4f, 0x70, 0x73, 0x2a,
	0x29, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x10, 0x0a, 0x0c, 0x48, 0x41, 0x53, 0x48, 0x5f,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x48, 0x41, 0x53,
	0x48, 0x5f, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x10, 0x01, 0x2a, 0x91, 0x01, 0x0a, 0x06, 0x4f,
	0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x4f, 0x50, 0x43, 0x4f, 0x44, 0x45, 0x5f,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x4f, 0x50, 0x43,
	0x4f, 0x44, 0x45, 0x5f, 0x50, 0x55, 0x53, 0x48, 0x5f, 0x49, 0x4e, 0x50, 0x55, 0x54, 0x10, 0x01,
	0x12, 0x15, 0x0a, 0x11, 0x4f, 0x50, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x50, 0x55, 0x53, 0x48, 0x5f,
	0x42, 0x59, 0x54, 0x45, 0x53, 0x10, 0x02, 0x12, 0x25, 0x0a, 0x21, 0x4f, 0x50, 0x43, 0x4f, 0x44,
	0x45, 0x5f, 0x50, 0x4f, 0x50, 0x5f, 0x43, 0x48, 0x49, 0x4c, 0x44, 0x52, 0x45, 0x4e, 0x5f, 0x48,
	0x41, 0x53, 0x48, 0x5f, 0x41, 0x4e, 0x44, 0x5f, 0x50, 0x55, 0x53, 0x48, 0x10, 0x03, 0x12, 0x1e,
	0x0a, 0x1a, 0x4f, 0x50, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x50, 0x4f, 0x50, 0x5f, 0x4e, 0x5f, 0x48,
	0x41, 0x53, 0x48, 0x5f, 0x41, 0x4e, 0x44, 0x5f, 0x50, 0x55, 0x53, 0x48, 0x10, 0x04, 0x42, 0x20,
	0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x73, 0x65,
	0x6b, 0x68, 0x61, 0x72, 0x2f, 0x68, 0x61, 0x73, 0x68, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hashmachine_proto_rawDescOnce sync.Once
	file_hashmachine_proto_rawDescData = file_hashmachine_proto_rawDesc
)

func file_hashmachine_proto_rawDescGZIP() []byte {
	file_hashmachine_proto_rawDescOnce.Do(func() {
		file_hashmachine_proto_rawDescData = protoimpl.X.CompressGZIP(file_hashmachine_proto_rawDescData)
	})
	return file_hashmachine_proto_rawDescData
}

var file_hashmachine_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_hashmachine_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_hashmachine_proto_goTypes = []interface{}{
	(Hash)(0),               // 0: Hash
	(OpCode)(0),             // 1: OpCode
	(*ProgramMetadata)(nil), // 2: ProgramMetadata
	(*Op)(nil),              // 3: Op
	(*Program)(nil),         // 4: Program
}
var file_hashmachine_proto_depIdxs = []int32{
	0, // 0: ProgramMetadata.hash:type_name -> Hash
	1, // 1: Op.opcode:type_name -> OpCode
	2, // 2: Program.metadata:type_name -> ProgramMetadata
	3, // 3: Program.Ops:type_name -> Op
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_hashmachine_proto_init() }
func file_hashmachine_proto_init() {
	if File_hashmachine_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hashmachine_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProgramMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashmachine_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Op); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashmachine_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Program); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hashmachine_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hashmachine_proto_goTypes,
		DependencyIndexes: file_hashmachine_proto_depIdxs,
		EnumInfos:         file_hashmachine_proto_enumTypes,
		MessageInfos:      file_hashmachine_proto_msgTypes,
	}.Build()
	File_hashmachine_proto = out.File
	file_hashmachine_proto_rawDesc = nil
	file_hashmachine_proto_goTypes = nil
	file_hashmachine_proto_depIdxs = nil
}
